### PR TITLE
[DO-NOT-MERGE-YET] Include scalar when possible

### PR DESCRIPTION
**Pull request by dscho**
This addresses the macOS-specific part of the project to include `contrib/scalar/`-based Scalar (if available) into the installers built in the `microsoft/git` fork.

### CODE REVIEW

**Comment by dscho** [comment]
@derrickstolee I _think_ it worked, based on what I see [here](https://github.com/dscho/git_osx_installer/runs/2477102463?check_suite_focus=true#step:6:2679). But I do not have a macOS machine at my disposal to test. Could I trouble you to do that?

**Comment by dscho** [comment]
I marked this as "DO-NOT-MERGE-YET" for several reasons:

- #4 should be merged first.
- I do want to have confirmation via manual testing that `scalar help`, `scalar clone` and `git help scalar` work as expected.
- The [`TO-DROP` commit](https://github.com/derrickstolee/git_osx_installer/pull/5/commits/86f7f91a4b143b5884645486bde213ee518ac270) needs to be dropped before this can be merged.

**Comment by derrickstolee** [comment]
> @derrickstolee I _think_ it worked, based on what I see [here](https://github.com/dscho/git_osx_installer/runs/2477102463?check_suite_focus=true#step:6:2679). But I do not have a macOS machine at my disposal to test. Could I trouble you to do that?

This worked! Of course, I found out by testing `scalar version`, which just shows the usage ;). Perhaps we should add that to our TODOs?

**Comment by dscho** [comment]
> 
> 
> > @derrickstolee I _think_ it worked, based on what I see [here](https://github.com/dscho/git_osx_installer/runs/2477102463?check_suite_focus=true#step:6:2679). But I do not have a macOS machine at my disposal to test. Could I trouble you to do that?
> 
> This worked! Of course, I found out by testing `scalar version`, which just shows the usage ;). Perhaps we should add that to our TODOs?

I am doing things very differently now: all that will be needed is to set `INCLUDE_SCALAR=YesPlease` (can be an environment variable, and is simply ignored if `contrib/scalar/` is not part of the source code).

So I'll abandon this PR.

**Pull request closed without merging**
